### ISSUE TITLE
Aify version 1.1 doesn't work with "Error: unable to connect"

### ISSUE THREAD

**Issue by city-zen** [ali-raheem/Aify#2]
Thanks for this promising Thunderbird addon

I downloaded, installed, configured and ran it

I was able to load my (working) OpenAI API key and choose GPT-4

I'm able to edit the prompts and I see Aify's button in the compose window

However, after selecting some text and choosing one of Aify's prompts I get a new window that immediately displays "Error: unable to connect"

Some info about my system, in case it's useful

OS: Windows 10 Home 
TB version: 102.11.0
Locale: es-ar
Several add-ons installed

This was also tested on another PC with very similar features in both hardware and software
It also failed with the same error

Let me know if I can provide more information that could be useful to solve this issue

Thanks

**Comment by ali-raheem** [comment]
Thank you this is so useful! And I've just seen your review on the Add on store.
(as we continue the troubleshooting on email I'll update steps here for others sake).

1. Can I check if you have clicked the save button at the bottom of the Settings page?
2. Please make sure the model selected is one you have access to (GPT-4 requires extra permissions from OpenAI).
3. Please make sure the API key remains when you close and reopen the settings page.
