### ISSUE TITLE
Feature request - Insert into email, automatically use email text

### ISSUE THREAD

**Issue by jfryton** [ali-raheem/Aify#3]
Hi there, great work! Wondering if it's possible to implement the ability to automatically generate based on the incoming email and to include functionality (or a button option) to insert the generated draft into the email to avoid having to copy/paste.

**Comment by vzaliva** [comment]
I want to second this request. I would love to have a button that will replace the selected part of the email (used as input to Aify) with generated text. Thanks!

**Comment by ali-raheem** [comment]
Addressed by #6
