### ISSUE TITLE
Error: Unable to retrieve data

### ISSUE THREAD

**Issue by cattin** [ali-raheem/Aify#8]
Hi,

This add--on looks realy interesting but I can not get it to work on Linux with Thunderbird 115.7.0. This despite having an OpenAI subscription... I alway get "Error: Unable to retrieve data"  no matter which model I try in the dialog. Can you help?

**Comment by ali-raheem** [comment]
Check #5  and report back if it's still not working.

**Comment by cattin** [comment]
Aaarrrrggg, my bad. I was not aware that there is a difference between a ChatGPT subscription and a deposit for OpenAI API... It workes now nicely. thanks.
